### ISSUE TITLE
How to generate the covariance matrix

### ISSUE THREAD

**Issue by 1667857557** [Thewhey-Brian/SCTWAS#1]
Hi,

  Thanks for your excellent work. We want to use the FUSION weights to generate the covariance matrix. Could you give us some suggestions? Also, we would like to ask whether this tool can be used in PWAS or cell-specific level TWAS (based on the same tissue). Thank you in advance.

Huang

**Comment by Thewhey-Brian** [comment]
Hi Huang,

Thank you for your interest in our work!

Regarding your query about generating the covariance matrix using FUSION weights, **there's no need for you to manually generate the covariance matrix**. The package already includes both "cov_matrix_GTEx_v7" and "cov_matrix_GTEx_v8" embedded. You can easily call these matrices by specifying "cov_matrix_GTEx_v7" or "cov_matrix_GTEx_v8" in "cov_matrix" parameter in "run_CSTWAS" function.

`res_CSTWAS = run_CSTWAS("path_to_TWAS_results", cov_matrix="cov_matrix_GTEx_v7", ...)`

As for your question regarding the application in PWAS or cell-specific level TWAS based on the same tissue, yes, CSTWAS can indeed be generalized to these contexts. However, it's important to note that the corresponding covariance matrix may need to be generated based on the specific reference data you're working with. 

For more detailed information, please refer to [our paper](https://doi.org/10.1016/j.xhgg.2024.100283). Should you have any further questions or require additional assistance, please don't hesitate to reach out. 

Best wishes,

Xinyu
